language: php

git:
    depth: 150

cache:
    directories:
        - vendor

dist: focal

matrix:
    include:
        - php: 8.1
          env:
              - COMPOSER_FLAGS='--prefer-lowest'
        - php: 8.1
        - php: 8.2
        - php: 8.3

install:
    - phpenv config-rm xdebug.ini
    - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'intl.default_locale = "pl"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer update -n $COMPOSER_FLAGS

script:
    - composer sniffer
    - composer cept build
    - composer stan
    - composer cept run unit $CODECEPT_ENV
    - composer cept run functional
