---
version: '3'

services:
    web:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: files
        environment:
            XDEBUG_CONFIG: 'idekey=PHPSTORM discover_client_host=false client_host=host.docker.internal'
            XDEBUG_MODE: 'debug'
            PHP_IDE_CONFIG: 'serverName=localhost'
            DOCROOT: '/var/www/application/tests/_support/project/public'
            HOST_UID: 1000
            HOST_GID: 1000
            APP_ENV: test
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/var/www/application
            - ~/.composer:/var/www/.composer
        extra_hosts:
            - "host.docker.internal:host-gateway"
